### PR TITLE
Version 5.0 for error component

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**
Design spec:
https://blackbaud.invisionapp.com/console/share/SV2YM7MR5Z/745226082

### CODE REVIEW

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Review by blackbaud-PendletonRouse — COMMENTED** [review]
@Blackbaud-AlexKingman can we update to the non-condensed font version for default `.sky-font-heading-1` ? Looks good aside from that.

**Review by blackbaud-PendletonRouse — COMMENTED** [review]
Correction: `.sky-font-heading-1` needs to be implemented for both modern and default themes

**Comment by Blackbaud-AlexKingman** [comment]
@blackbaud-PendletonRouse 

> Correction: `.sky-font-heading-1` needs to be implemented for both modern and default themes

Sorry, not sure I follow. Right now, `.sky-font-heading-1` is being used for the title on both modern and default themes. Is something wrong with that?

**Comment by Blackbaud-ToddRoberts** [comment]
It's mapped to a condensed font in default. We'd need up update it in theme, but it would be a blanket change.

**Review by blackbaud-PendletonRouse — APPROVED** [review]
@Blackbaud-AlexKingman you're good to go with the existing type styles :)

**Pull request merged**
