### PR TITLE
Demo for error component

### PR DESCRIPTION
**Pull request by Blackbaud-AlexKingman**

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-error-demo](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-error-demo)

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-error-demo](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-error-demo)

**Review by blackbaud-johnly — COMMENTED** [review]
When I view the PR preview link, I don't see a demo. I see code examples, but not a demo. Am I missing something.

**Review by Blackbaud-DeniseCisneros — APPROVED** [review]

**Comment by Blackbaud-AlexKingman** [comment]
> When I view the PR preview link, I don't see a demo. I see code examples, but not a demo. Am I missing something.

We didn't have one before. I was using the current site as a guideline: https://developer.blackbaud.com/skyux/components/error

**Review by blackbaud-johnly — APPROVED** [review]

**Pull request merged**
