### PR TITLE
Updating docs illustrations

### PR DESCRIPTION
**Pull request by blackbaud-PendletonRouse**
Updating to modern illustrations

### CODE REVIEW

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations)

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations)

**Review by Blackbaud-SteveBrush — COMMENTED** [review]
The new error images are only being applied to the `5.0.0` version of `@skyux/errors`. Not sure how this affects this PR, but thought I'd bring it up.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations)

**Comment by blackbaud-johnly** [comment]
@Blackbaud-SteveBrush, are we going to apply the new images to SKY UX 4 at any point, or is this only going to be in version 5? If the former, do you think there's any harm in updating the images in the docs BEFORE we update version 4? If the latter, how soon do you think we'll be working on archiving the SKY UX 4 version of the site? It seems like if we aren't going to update the images in version 4 but are going to split the site up soon, maybe we should just hold off on these doc updates for now.

Also, @blackbaud-PendletonRouse, the new Anatomy image is slightly off. The dark green #1 circle in the image needs to be moved up. It looks like you updated the graphic and error text in the image but didn't move the corresponding numbers. Right now, #1 is beside the description, not the title. FWIW, I'd also reposition #3 just a tad to basically be in the same spot where #1 currently is because we usually put the numbers to the top right of the item that they identify when that's possible.

**Comment by blackbaud-johnly** [comment]
@blackbaud-PendletonRouse, I noticed a couple other things when reviewing the images...
1. In the *Options* section, the first two images don't have a border on the bottom in my PR preview. Not sure if that's just a blip on my end. Do you see the same thing?
2. Also in the *Options* section, the images all have the same *Try again* action. That doesn't seem right. It's been a while since we reworked the error text, but I'm almost certain we fixed the images to NOT have the same action for all errors. For example, a *Try again* action doesn't make sense for 404 errors in the third example or in the restricted access error in the fourth example. Is this just a miss on the updated images, or did the dev work to update the error messages miss this? @Blackbaud-AlexKingman , I think you implemented the updated error messages. Do you know if we changed the action at the end on some of them? I checked the Stackblitz examples, but they are still displaying the old versions.
3. At the end of the *Options* section, do we need to update the headline font and description fonts in the last image that illustrates an error message without an image or action? That image is still using the old styles. I assume the fonts should be updated in this scenario just like in the default error messages, but I'm not sure.

**Comment by blackbaud-PendletonRouse** [comment]
> @Blackbaud-SteveBrush, are we going to apply the new images to SKY UX 4 at any point, or is this only going to be in version 5? If the former, do you think there's any harm in updating the images in the docs BEFORE we update version 4? If the latter, how soon do you think we'll be working on archiving the SKY UX 4 version of the site? It seems like if we aren't going to update the images in version 4 but are going to split the site up soon, maybe we should just hold off on these doc updates for now.
> 
> Also, @blackbaud-PendletonRouse, the new Anatomy image is slightly off. The dark green #1 circle in the image needs to be moved up. It looks like you updated the graphic and error text in the image but didn't move the corresponding numbers. Right now, #1 is beside the description, not the title. FWIW, I'd also reposition #3 just a tad to basically be in the same spot where #1 currently is because we usually put the numbers to the top right of the item that they identify when that's possible.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations)

**Comment by blackbaud-PendletonRouse** [comment]
@blackbaud-johnly I added the border back to the screens in question and fixed the anatomy screen. @Blackbaud-ToddRoberts can you answer John's question re: the language on error actions? "The images all have the same Try again action. That doesn't seem right. It's been a while since we reworked the error text, but I'm almost certain we fixed the images to NOT have the same action for all errors. For example, a Try again action doesn't make sense for 404 errors in the third example or in the restricted access error in the fourth example. Is this just a miss on the updated images, or did the dev work to update the error messages miss this?"

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations)

**Comment by blackbaud-johnly** [comment]
@blackbaud-PendletonRouse, the borders and Anatomy numbers look good now.

What about the question on the last image in the *Options* section? The headline font still follows the old style. I can't tell if the description is font changes in the updated error messages, but shouldn't we update the headline font (and maybe description font) in that image to match the others?

Also, I just touched base with Steve, and as far as he knows, the new error styles and images will not ever be applied to SKY UX 4. If that's the case, I think we need to shelve these updates until we have the 5.0 version of the site. The plan is to archive the 4.0 version of the site and make it available through a separate PR, and then Paul and Steve are going to go through and rip out the content that no longer applies to 5.0 and have me review the updated docs. If these new error messages only apply to 5.0, I think we need to wait until we have the 5.0 site in place. That said, Steve wasn't 100 percent sure that the updated error messages won't ever be applied to 4.0 and recommended asking @Blackbaud-ToddRoberts. Todd, do you know if these error message updates are for 5.0 only?

**Comment by blackbaud-PendletonRouse** [comment]
@blackbaud-johnly Updated the non-illustration image. Also, yes, I believe we can shelve these until the version 5 doc site is available. @Blackbaud-PaulCrowder can confirm, as Steve missed that stand up.

**Comment by blackbaud-ado** [comment]
Preview build at [https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations](https://developer.blackbaud.com/skyux-errors?_sp.spa=pr-Updated-error-illustrations)

**Review by Blackbaud-SteveBrush — APPROVED** [review]

**Pull request merged**
